name: cotality-capstone-q1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - geopandas
  - rasterio
  - rioxarray
  - xarray
  - pyproj
  - requests
  - shapely
  - matplotlib
  - nbformat
  - netcdf4
  - plotly
  - pyarrow
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - pip


