[project]
name = "cotalityq1capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dask>=2025.11.0",
    "geopandas>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "rasterio>=1.4.3",
    "tqdm>=4.67.1",
    "xarray>=2025.11.0",
]
